### ISSUE TITLE
Question: How to pass data from async method in SupplyData?

### ISSUE THREAD

**Issue by naveedahmed1** [MintPlayer/MintPlayer.AspNetCore.SpaServices#42]
The docs provide a sample code to pass data from .net core app to Angular app:

```
app.UseSpa(spa =>
    {
        ...
        
        spa.UseSpaPrerendering(options =>
        {
            ...

            options.SupplyData = (context, data) =>
            {
                var route = spaRouteService.GetCurrentRoute(context);
                var personRepository = context.RequestServices.GetRequiredService<IPersonRepository>();

                switch (route?.Name)
                {
                    case "person-list":
                        {
                            var people = personRepository.GetPeople();
                            data["people"] = people;
                        }
                        break;
                    case "person-show":
                    case "person-edit":
                        {
                            var id = System.Convert.ToInt32(route.Parameters["id"]);
                            var person = personRepository.GetPerson(id);
                            data["person"] = person;
                        }
                        break;
                }
            };
        });
```

This works for synchronous operation, what if `personRepository.GetPeople();` is an async function. Can you please guide how to use async method of a repository in `SupplyData`? While also keeping in mind that `HttpContext isn't thread safe` https://learn.microsoft.com/en-us/aspnet/core/fundamentals/use-http-context?view=aspnetcore-7.0#httpcontext-isnt-thread-safe

Thank you.

**Comment by PieterjanDeClippel** [comment]
@naveedahmed1 In this library, `SupplyData` was replaced with a service-implementation method called `OnSupplyData`. This repository (.NET 6 and .NET 7) includes an example [here](https://github.com/MintPlayer/MintPlayer.AspNetCore.SpaServices/blob/master/Demo/Demo.Web/Services/DemoSpaPrerenderingService.cs#L38).

This implementation has the following benefits over the .NET31 version:
- The `OnSupplyData` method can be async
- You can perform Dependency Injection in an encapsulated class, not in the `Startup` anymore
- You have the option of registering routes, and determine what route (angular page) was activated with its parameters

**Comment by naveedahmed1** [comment]
Thank you so much @PieterjanDeClippel for the detailed reply and your hard work, really appreciate.

**Comment by naveedahmed1** [comment]
One more question, is it necessary to declare Angular routes in .Net Core app as well?

We can determine the current url and its parameters from `HttpContext` parameter in `OnSupplyData` right?

**Comment by PieterjanDeClippel** [comment]
> Is it necessary to declare Angular routes in .Net Core app as well?

Nope
 
> We can determine the current url and its parameters from `HttpContext` parameter in `OnSupplyData` right?

Nope. You have to extract the activated url as demonstrated [here](https://github.com/MintPlayer/MintPlayer.AspNetCore.SpaServices/blob/master/MintPlayer.AspNetCore.SpaServices.Routing/Services/SpaRouteService.cs#L318)

**Comment by naveedahmed1** [comment]
Thank you, I am already using `context.Features` for path.

> // For an angular app the context.Request.Path instruction returns
		// - The correct path in Development mode
		// - index.html in Production mode
		// The RawTarget private property contains the real path visited by the user at any time.

Is it true for the `context.Request.Host.Host` and ``context.Request.Scheme`` as well?

**Comment by PieterjanDeClippel** [comment]
> Thank you, I am already using `context.Features` for path.
> 
> > // For an angular app the context.Request.Path instruction returns
> > // - The correct path in Development mode
> > // - index.html in Production mode
> > // The RawTarget private property contains the real path visited by the user at any time.
> 
> Is it true for the `context.Request.Host.Host` and `context.Request.Scheme` as well?

No idea tbf. Never needed that in my webapps

**Comment by naveedahmed1** [comment]
Ok, Thank you so much once again!

**Comment by PieterjanDeClippel** [comment]
[See also](https://github.com/MintPlayer/MintPlayer.AspNetCore.SpaServices/blob/master/MintPlayer.AspNetCore.NodeServices/Content/Node/entrypoint-http.js#L178)

**Comment by naveedahmed1** [comment]
My use case is little different, I need the `host` value to properly populate the `canonical` tag in my html. Currently I use the value of `context.Request.Host.Host` and pass it to my Angular app which uses it to generate html meta tag for `canonical` url.

**Comment by PieterjanDeClippel** [comment]
![image](https://github.com/MintPlayer/MintPlayer.AspNetCore.SpaServices/assets/9629574/f43a1203-2246-42ed-8bef-d43fdca684bd)

[This](https://github.com/MintPlayer/MintPlayer/blob/master/MintPlayer.Web/ClientApp/src/app/helpers/html-link.helper.ts#L32) somehow seems to be working fine for me

**Comment by naveedahmed1** [comment]
Probably because of:

https://github.com/MintPlayer/MintPlayer.AspNetCore.SpaServices/blob/8e855ed3f03b277d473b428d2d7af6896f0a1b98/MintPlayer.AspNetCore.SpaServices.Prerendering/Prerendering/SpaPrerenderingExtensions.cs#L175

and 

https://github.com/MintPlayer/MintPlayer.AspNetCore.SpaServices/blob/8e855ed3f03b277d473b428d2d7af6896f0a1b98/MintPlayer.AspNetCore.SpaServices.Prerendering/Prerendering/SpaPrerenderingExtensions.cs#L232

**Comment by PieterjanDeClippel** [comment]
So what you can do here is

- Install ng-seo

    npm i @mintplayer/ng-seo

- Provide the `BOOT_FUNC_PARAMS` from the `main.server.ts`

[link](https://github.com/MintPlayer/MintPlayer/blob/master/MintPlayer.Web/ClientApp/src/main.server.ts#L21)

- Load the `SeoModule`:

[Link](https://github.com/MintPlayer/mintplayer-ng-seo/blob/master/apps/seo-demo/src/app/pages/home/home.module.ts#L11)

- Use the `SeoDirective` on your pages:

[Link](https://github.com/MintPlayer/mintplayer-ng-seo/blob/master/apps/seo-demo/src/app/pages/home/home.component.html#L2)

**Comment by naveedahmed1** [comment]
Ok, Thank you!

**Comment by naveedahmed1** [comment]
@PieterjanDeClippel I have one more question:

In `OnSupplyData`, we fetch data from database and pass it to Angular app.

For cases when there isn't any record found, we would want to return immediately let say with a 404 status code and a quick html message showing Page Not Found.

Can we do that in OnSupplyData?

 Similarly for 301 redirects, can we do that in OnSupplyData?

**Comment by PieterjanDeClippel** [comment]
An example of a redirect is [here](https://github.com/MintPlayer/MintPlayer.AspNetCore.SpaServices/blob/master/Demo/Demo.Web/Services/DemoSpaPrerenderingService.cs#L92)

**Comment by naveedahmed1** [comment]
Thanks, yes I was also going through your comment above https://github.com/MintPlayer/MintPlayer.AspNetCore.SpaServices/issues/42#issuecomment-1681063184

But I was wondering will it still start the Angular App or will it return immediately without doing any further processing and launching Angular app?

**Comment by PieterjanDeClippel** [comment]
It will start the angular app, yes. And return it with the statuscode you supply.

You can try [this url](https://mintplayer.com/artist/500/example-slug) for example, using [this tool](https://httpstatus.io)

The (pretty stale) website does not yet:
- Client-side: show a loading indicator
- Client and SSR: display a not-found component and hide everything else when loading has finished or during SSR

**Comment by PieterjanDeClippel** [comment]
You can use `TransferState` to prevent critical data (like a custom background color) from flickering your page.

**Comment by naveedahmed1** [comment]
What if I don't want the Angular app to even start in case of error?

**Comment by naveedahmed1** [comment]
Especially in case of 301 redirect there's no point of even starting the angular app, what do you think?

**Comment by naveedahmed1** [comment]
Something similar to this:
```
 context.Response.StatusCode = removedPermanently ? StatusCodes.Status410Gone : StatusCodes.Status404NotFound;
 context.Response.ContentType = "text/html";
 string errorNotFound = "Page Not Found";
 await context.Response.WriteAsync(errorNotFound);
```
And then shortcircut, stop further processing.

**Comment by PieterjanDeClippel** [comment]
What? No! the angular app runs all the time.

I meant "serve" in my previous comment

**Comment by naveedahmed1** [comment]
In my opinion running Angular app in case of 301 redirects or 404, would be an extra and unnecessary work.

**Comment by PieterjanDeClippel** [comment]
Then you should write a middleware before the `UseSpa` middleware which checks if the item exists, and doesn't call the `await next()` middleware if the item doesn't exist. 

But then a visitor will just get a blank page if something was removed, and he wouldn't know what to do to search the rest of the website. User-friendliness < 0

Also if a user navigates to this url through your angular site, from another page, then he'll see the angular app. Then hits F5 to refresh, then sees a blank page.

**Comment by naveedahmed1** [comment]
Yes you have a valid point for 404 pages but in case of 301 maybe a middleware could a better option.

Any plans to add support for early hints?

**Comment by PieterjanDeClippel** [comment]
There's a valid point you're making. It seems that when a redirect is due:

1) asp.net core doesn't return the preferred statuscode (perhaps because of the response.onstarting)
2) the middleware still send the webrequest to express and node is still invoking the bootmodule, just to have it redirect immediately

**Comment by naveedahmed1** [comment]
For me this seems to be working with 301 status code in dev env:

```
context.Response.OnStarting(() =>
{
    context.Response.Redirect(redirectURL, true);
    return Task.CompletedTask;
});
```

But it redirects after Angular app has finished generating the response.

Even this seems to be working fine:

```
context.Response.OnStarting(() =>
{
    context.Response.StatusCode = removedPermanently ? StatusCodes.Status410Gone : StatusCodes.Status404NotFound;
    return Task.CompletedTask;
});
```

**Comment by naveedahmed1** [comment]
It seems sometimes .Net Core routes are also being intercepted by the Prerendering.

I have defined .Net Core routes above `app.UseSpa`, but its still sometimes hitting the Angular app.

**Comment by PieterjanDeClippel** [comment]
Is your app a PWA (eg using @angular/pwa) ?

**Comment by PieterjanDeClippel** [comment]
@naveedahmed1 

> Especially in case of 301 redirect there's no point of even starting the angular app, what do you think?

I released a new version for .NET 8 which does NOT render the application in case of a redirect:

![image](https://github.com/MintPlayer/MintPlayer.AspNetCore.SpaServices/assets/9629574/afa7a5a9-5fa1-4b30-b3ac-65be8c37722d)
