### ISSUE TITLE
Support for .NET 8

### ISSUE THREAD

**Issue by jitterbox** [MintPlayer/MintPlayer.AspNetCore.SpaServices#49]
Microsoft is offering a go-live license as of RC2, it would be great to have support for .NET 8 and an implementation guide that covers their latest Angular project templates.

**Comment by PieterjanDeClippel** [comment]
I published an RC just now. However, I haven't succeeded in setting up a multi-version-support repository yet.

Wondering how they ensure that pull-requests are merged in the correct order into the release branches, and start from an up-to-date base

**Comment by PieterjanDeClippel** [comment]
Released yesterday
